mini_app/urls.py
from django.urls import path
from . import views
app_name = 'mini_app'


urlpatterns = [
    path('', views.home, name='home'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('login', views.userLogin, name='login'),
    path('addItem', views.addItem, name='add'),
    path('loggedOut', views.userLogout, name='logout'),
    path('deleted/<int:pk>', views.itemDelete, name='delete'),

]

minicrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mini_app.urls')),
]

mini_app/models.py
from queue import Empty
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class MiniCrud(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    age = models.IntegerField()
    manager = models.ForeignKey(
        User, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name + ' has been created by ' + self.manager.first_name

mini_app/views.py
import email
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from . models import MiniCrud
from django.contrib.auth.models import User

# Create your views here.


def home(request):
    fields = MiniCrud.objects.all()
    return render(request, 'mini_app/home.html', {'fields': fields})


@login_required
def itemDelete(request, pk):
    # fields = MiniCrud.objects.all()
    profile = MiniCrud.objects.get(pk=pk)
    profile.delete()
    # return render(request, 'mini_app/home.html', {'fields': fields})
    return redirect('mini_app:home')
    # return reverse('mini_app:home')


@login_required
def edit(request, pk):

    profile = MiniCrud.objects.get(pk=pk)
    if request.method == 'POST':
        first_name = (request.POST['first_name']).strip()
        last_name = (request.POST['last_name']).strip()
        new_email = (request.POST['email']).strip()
        profile.email = new_email
        profile.first_name = first_name
        profile.last_name = last_name
        profile.save
        print(first_name+last_name+new_email)
    return render(request, 'mini_app/edit.html', {'profile': profile})


@login_required
def addItem(request):
    if request.method == 'POST':
        first_name = (request.POST['first_name']).strip()
        last_name = (request.POST['last_name']).strip()
        new_email = (request.POST['email']).strip()
        age = request.POST['age']
        manager = request.POST['manager']

        manager = User.objects.get(username=manager)
        m = MiniCrud(first_name=first_name, last_name=last_name,
                     email=new_email, age=age, manager=manager)
        m.save()
        fields = MiniCrud.objects.all()
        return render(request, 'mini_app/home.html', {'fields': fields})
    else:
        return render(request, 'mini_app/create.html')


def userLogin(request):
    fields = MiniCrud.objects.all()
    if request.method == 'POST':
        username_passed = request.POST['username']
        password__passed = request.POST['password']
        user = authenticate(request, username=username_passed,
                            password=password__passed)
        if user is not None:
            login(request, user)
            # Redirect to a success page.

            return redirect('mini_app:home')
    else:
        # Return an 'invalid login' error message.
        return render(request, 'mini_app/login.html')


def userLogout(request):
    logout(request)
    # fields = MiniCrud.objects.all()
    # Redirect to a success page.
    return redirect('mini_app:home')
    # return redirect(request, 'mini_app/home.html', {'fields': fields})

mini_app/templates/mini_app/create.html
{% extends "base.html" %} {% block header-footer %} {% load static %}<p class="mt-2 text-end">You are working as <span
        class="text-info">{{user.first_name}}</span></p>
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="fs-4 "><i class="bi bi-person-circle"></i>
            <span class="text-info">Add</span>user
        </h1>
        <form action="" method="post"> {% csrf_token %} <div class="mb-3">
                <label for="first_name" class="col-form-label" id="firstname_label">First Name:</label>
                <input class="form-control" type="text" name="first_name" id="first_name" placeholder="First Name">
            </div>
            <div class="mb-3">
                <label for="last_name" class="col-form-label" id="lastname_label">Last Name:</label>
                <input class="form-control" type="text" name="last_name" id="last_name" placeholder="Last Name">
            </div>
            <div class="mb-3">
                <label for="email" class="col-form-label" id="email_label">Email:</label>
                <input class="form-control" type="email" name="email" id="email" placeholder="Email">
            </div>
            <div class="mb-3">
                <label for="age" class="col-form-label" id="age_label">Age:</label>
                <input class="form-control" type="number" name="age" id="age" placeholder="Age">
            </div>
            <div class="mb-3">
                <!-- <label for="manager" class="col-form-label">Added by:</label> -->
                <input class="form-control" type="hidden" name="manager" id="manager" value="{{user}}">
            </div>
            <div class="">
                <button class="mt-3 btn btn-outline-info" type="submit" id="mybtn">Add</button>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'mini_app/create.js'%}"></script> {% endblock header-footer %}

mini_app/templates/mini_app/edit.html
{% extends "base.html" %} {% block header-footer %} {% load static %} <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="fs-4 "><i class="bi bi-person-circle"></i>
            <span class="text-info">Pro</span>file
        </h1>
        <p class="notification">First Name: <span id="name_first">{{profile.first_name}}</span> </p>
        <p class="notification">Last Name: <span id="name_last">{{profile.last_name}}</span></p>
        <p class=" notification"> Email: <span id="myemail">{{profile.email}}</span> </p>
        <h2 class=" fs-5 mt-5">Edit Profile</h2>
        <form action="" method="post"> {% csrf_token %} <div class="mb-3">
                <label for="first_name" class="col-form-label" id="firstname_label">First Name: <span
                        class="text-danger" id="firstname_note"></span></label>
                <input class="form-control" type="text" name="first_name" id="first_name" placeholder="First Name"
                    value="{{profile.first_name}}">
            </div>
            <div class="mb-3">
                <label for="last_name" class="col-form-label" id="lastname_label">Last Name: </label>
                <input class="form-control" type="text" name="last_name" id="last_name" placeholder="Last Name"
                    value="{{profile.last_name}}">
            </div>
            <div class="mb-3">
                <label for="email" class="col-form-label" id="email_label">Email:</label>
                <input class="form-control" type="email" name="email" id="email" placeholder="Email"
                    value="{{profile.email}}">
            </div>
            <div class="">
                <button class="mt-3 btn btn-outline-info" type="submit" id="mybtn">Update</button>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'mini_app/update.js' %}"></script> {% endblock header-footer %}

mini_app/templates/mini_app/home.html
{% extends "base.html" %} {% block header-footer %}
<!-- <div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
    </div>
</div>   --> {% if user.is_authenticated %} <p class="mt-2 text-end">Welcome <span
        class="text-info">{{user.first_name}}</span></p> {% endif %} <div
    class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5 m-1"> {% for item in fields %} <div
        class="col d-flex align-items-start mb-3 ">
        <div class="lh-1">
            <h1 class="fs-4 "><i class="bi bi-person-circle"></i>
                <span class="text-info">Pro</span>file
            </h1>
            <p class="">First Name: {{item.first_name}} </p>
            <p class="">Last Name: {{item.last_name}} </p>
            <p class="">Age: {{item.age}} </p>
            <p class="">Email: {{item.email}} </p> {% if user.is_authenticated %} <p class="">Managed by:
                {{item.manager.first_name}} </p> <a class="btn btn-outline-info"
                href="{% url 'mini_app:edit' item.pk %}">Edit</a>
            <a class="btn btn-outline-info" href="{% url 'mini_app:delete' item.pk %}">Delete</a> {% endif %}
        </div>
    </div> {% endfor %} {% endblock header-footer %} </div>
<!-- {% if user == item.manager %} {% endif %} this is a filter condition -->

mini_app/templates/mini_app/login.html
{% extends "base.html" %} {% block header-footer %} {% load static %}<div class="container mt-5 text-center"
    style="max-width: 500px;">
    <main class="form-signin w-100 m-auto pt-5">
        <form method="POST"> {% csrf_token %} <h1 class="fs-1 mb-4"><i class="bi bi-person-circle text-info"></i>
            </h1>
            <h1 class="h3 mb-3 fw-normal text-secondary" id="example">Please sign in</h1>
            <div class="form-floating">
                <input type="text" class="form-control" id="username" placeholder="Username" name="username">
                <label for="username">User Name</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="password" placeholder="Password" name="password">
                <label for="password">Password</label>
            </div>
            <button class="w-100 btn btn-lg btn-primary mt-4" type="submit">Sign in</button>
        </form>
    </main>
</div>
<script src="{% static 'mini_app/script.js' %}"></script> {% endblock header-footer %}

templates/base.html
<!DOCTYPE html>
<html lang="en"> {% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MiniCrud</title>
    <link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/512/889/889091.png" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>

<body>
    <div class="container py-4">
        <nav class="navbar navbar-expand-lg bg-light rounded fs-4 shadow-sm" aria-label="Eleventh navbar example">
            <div class="container-fluid">
                <a class="navbar-brand text-secondary fs-3 fw-bold" href="{% url 'mini_app:home' %}">Mini<span
                        class="text-info">Crud</span></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarsExample09">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0"> {% if not user.is_authenticated %} <li
                            class="nav-item">
                            <a class="nav-link active text-secondary" aria-current="page"
                                href="{% url 'mini_app:login' %}">Login</a>
                        </li> {% endif %} {% if user.is_authenticated %} <li class="nav-item">
                            <a class="nav-link text-secondary" href="{% url "mini_app:logout" %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary" href="{% url "mini_app:add" %}">Add</a>
                        </li> {% endif %}
                    </ul>
                    <form role="search">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                    </form>
                </div>
            </div>
        </nav> {% block header-footer %} {% endblock header-footer %} <div class="text-center mt-5"
            style="width: 100%;">
            <footer class="pt-3 mt-4 text-muted border-top"> © 2021 </footer>
        </div>
    </div>
    <!-- ------- JS --- -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>